### ISSUE TITLE
API No Longer Works

### ISSUE THREAD

**Issue by PCTipsGR** [PlanetGamingGG/myownfreehost-mild-api-client#2]
Seems like the API is no longer working, I tried [this URL](https://mofh.tariktunaikartukredit.cf/api-v2/public/availability.public.php?domain=planetcloudhosting.cf&response_type=pretty) and got the following message:

> Whoops! This server is not whitelisted.

You should probably consider whitelisting your own server :joy:

**Comment by PCTipsGR** [comment]
@PlanetGamingGG is it supposed to be no longer working?

**Comment by PCTipsGR** [comment]
I thought you said:

> We choose not to host the API on BYET.

:rofl:

**Comment by PCTipsGR** [comment]
Anyway, it is still showing as not whitelisted @PlanetGamingGG

**Comment by PlanetGamingGG** [comment]
@PCTipsGR We do not host this API on BYET.
It is now fixed.
Please try again and try clearing your cache if problem presist.
